

(defun testing ()
  (setf path (make-pathname :name "myoutput"))
  (setf output481 (open path :direction :output :if-exists :supersede))
   (print "These are the CS481 test cases for Assn3-23" output481)
   (print "These are the CS481 test cases for Assn3-23" output481)
   (terpri)
   (print  '(intersect '(426) '(2 a 30 6))  output481)
   (print  (intersect '(426) '(2 a 30 6))  output481) 
   (print '(intersect '(5 a j 4 c) '(b k 4 j 5)) output481)
   (print  (intersect '(5 a j 4 c) '(b k 4 j 5)) output481)
   (print '(intersect '(a b r f e) '(b r f e a)) output481)
   (print (intersect '(a b r f e) '(b r f e a)) output481)
   
   (print '(remove_duplicates '(3 5 a h 6 4 a 5 7 5)) output481)
   (print (remove_duplicates '(3 5 a h 6 4 a 5 7 5)) output481)
   (print '(remove_duplicates '(7 f 4 f 7 d d f)) output481)
   (print (remove_duplicates '(7 f 4 f 7 d d f)) output481)
   (print '(remove_duplicates '(7 f 4 8 c d)) output481)
   (print (remove_duplicates '(7 f 4 8 c d)) output481)

   (print '(get_distance "septer" "venus") output481)
   (print (get_distance "septer" "venus") output481)
   (print '(get_distance "mars" "venus") output481)
   (print (get_distance "mars" "venus") output481)
   (print '(get_distance "mars" "urie") output481)
   (print (get_distance "mars" "urie") output481)

   (print '(get_planets_by_means "mars" 'ROCKET) output481)
   (print (get_planets_by_means "mars" 'ROCKET) output481)
   (print '(get_planets_by_means "mars" 'TRANSPORTER) output481)
   (print (get_planets_by_means "mars" 'TRANSPORTER) output481)
   (print '(get_planets_by_means "roan" 'LASER) output481)
   (print (get_planets_by_means "roan" 'LASER) output481)
   (print '(get_planets_by_means "bernar" 'LASER) output481)
   (print (get_planets_by_means "bernar" 'LASER) output481)
   (print '(get_planets_by_means "bernar" 'ROCKET) output481)
   (print (get_planets_by_means "bernar" 'ROCKET) output481)

   (print '(construct_action_list "baggor") output481)
   (print (construct_action_list "baggor") output481)
   (print '(construct_action_list "mars") output481)
   (print (construct_action_list "mars") output481)
   (print '(construct_action_list "bernar") output481)
   (print (construct_action_list "bernar") output481)
    (print '(construct_action_list "roan") output481)
    (print (construct_action_list "roan") output481)
    
   (print 'Done output481)
   (close output481) 
   T )

